In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

generate a random matrix

In [12]:
a = np.random.randint(0,10, size=(8,8))
a

array([[8, 6, 1, 1, 6, 4, 8, 2],
       [2, 4, 6, 1, 1, 8, 3, 8],
       [8, 8, 7, 8, 1, 7, 1, 8],
       [3, 2, 0, 7, 3, 1, 4, 3],
       [3, 0, 8, 3, 2, 5, 6, 9],
       [0, 6, 9, 7, 8, 7, 9, 3],
       [5, 2, 0, 4, 3, 1, 4, 0],
       [4, 7, 1, 6, 2, 7, 4, 9]])

generate a random vector

In [13]:
b = np.random.randint(0,10, size=(8,1))
b

array([[3],
       [6],
       [2],
       [0],
       [2],
       [6],
       [8],
       [2]])

solve the poblem using np.linalg.solve

In [18]:
x = np.linalg.solve(a,b)
x

array([[ 0.59867171],
       [-1.44992639],
       [-0.43188938],
       [ 1.45176187],
       [-5.46035555],
       [ 4.56502338],
       [ 3.47887251],
       [-3.71931406]])

In [17]:
a.dot(x)

array([[3.],
       [6.],
       [2.],
       [0.],
       [2.],
       [6.],
       [8.],
       [2.]])

checking the correctness of the solution

In [19]:
np.allclose(np.dot(a, x), b)

True